config/routes.rb
Rails.application.routes.draw do
  resources :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      redirect_to tool_path(@tool.id)
    else
      render :new
    end
  end


  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool.id)
    else
      render :edit
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for(tool) do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :price %>
  <%= f.text_field :price %></p>
  <p><%= f.label :quantity %>
  <%= f.text_field :quantity %></p>
  <p><%= f.submit "GO!" %></p>
<% end %>

app/views/tools/edit.html.erb
<%= render partial: "form", locals: {tool: @tool} %>

app/views/tools/index.html.erb
<h1>All Tools</h1>

<%= link_to "Create New Tool", new_tool_path %>
<% @tools.each do |tool| %>
  <p><%= link_to "#{tool.name}", tool_path(tool.id) %> - <%= tool.quantity %></p>
<% end %>

app/views/tools/new.html.erb
<%= render partial: "form", locals: {tool: @tool} %>

app/views/tools/show.html.erb
<h1><%= @tool.name %> - <%= @tool.quantity %></h1>
<h3><%= @tool.price.round %></h3>
<%= link_to "Edit", edit_tool_path(@tool.id) %>
<%= link_to "Delete", tool_path(@tool.id), method: :delete %>